# Generated by Django 4.0.3 on 2022-03-30 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ชื่อหมวดหมู่สินค้า', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(help_text='ไซส์สินค้า', max_length=10)),
                ('gender', models.CharField(choices=[('1', 'MAN'), ('2', 'FEMALE')], help_text='เพศ', max_length=2)),
                ('shoulder_width', models.DecimalField(decimal_places=2, help_text='ความกว้างของหัวไหล่(cm)', max_digits=4)),
                ('sleeve_length', models.DecimalField(decimal_places=2, help_text='ความยาวของแขนเสื้อ(cm)', max_digits=4)),
                ('back_length', models.DecimalField(decimal_places=2, help_text='ความยาวด้านหลังเสื้อ(cm)', max_digits=4)),
                ('neck', models.DecimalField(decimal_places=2, help_text='รอบคอ(cm)', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ชื่อสินค้า', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='ราคาสินค้า', max_digits=4)),
                ('description', models.TextField(help_text='รายละเอียดสินค้า')),
                ('amount', models.IntegerField(help_text='จำนวนสินค้า')),
                ('is_active', models.BooleanField(default=True, help_text='สถานะสินค้า')),
                ('category', models.ForeignKey(blank=True, help_text='หมวดหมู่สินค้า', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('size', models.ForeignKey(blank=True, help_text='ไซส์เสื้อ', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size')),
            ],
        ),
    ]
