# Generated by Django 4.0.3 on 2022-03-30 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='จำนวนสินค้าที่สั่งซื้อ')),
                ('price', models.DecimalField(decimal_places=2, help_text='ราคาสินค้าที่สั่งซื้อ', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(help_text='ที่อยู่สำหรับจัดส่งสินค้า')),
                ('phone', models.CharField(help_text='เบอร์โทรศัพท์สำหรับติดต่อกลับ', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pending_date', models.DateTimeField(blank=True, help_text='วันที่สั่งซื้อสินค้า', null=True)),
                ('completed_date', models.DateTimeField(blank=True, help_text='วันที่สั่งซื้อสินค้าเสร็จสิ้น', null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, help_text='วันที่สั่งซื้อสินค้าถูกยกเลิก', null=True)),
            ],
        ),
    ]
