# Generated by Django 4.0.3 on 2022-03-30 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='ผู้ที่ทำรายการสั่งซื้อ', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(blank=True, help_text='สินค้าที่สั่งซื้อ', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='sale_transaction',
            field=models.ForeignKey(blank=True, help_text='รายการสั่งซื้อสินค้า', null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.saletransaction'),
        ),
    ]
